services:
  # Production service - Optimized static site serving
  production:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    image: casino-portal:3.0.0
    container_name: casino-portal
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    labels:
      - "com.docker.desktop=production"
      - "version=3.0.0"
      - "mode=static"
    networks:
      - casino-net

  # Development service (optional - for local dev)
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    image: casino-portal-dev:3.0.0
    container_name: casino-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app:delegated
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - ASTRO_TELEMETRY_DISABLED=1
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - casino-net
    profiles:
      - development

volumes:
  casino-test-db-data:
    driver: local
  casino-redis-data:
    driver: local

networks:
  casino-net:
    driver: bridge
    name: casino-network
    ipam:
      config:
        - subnet: 172.25.0.0/16
    labels:
      - "architecture=oop-compliant"
      - "version=2.0.0"
