version: '3.8'
services:
  dev:
    build: .
    image: best-casino-portal-dev:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app:delegated
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    labels:
      - "com.docker.desktop=dev-only"
  lighthouse:
    build:
      context: .
      dockerfile: Dockerfile.lighthouse
    image: best-casino-lighthouse:latest
    depends_on:
      - dev
    volumes:
      - ./reports:/reports
    entrypoint: ["npx","lighthouse","http://dev:3000","--output","html","--output-path","/reports/lighthouse.html","--output","json","--output-path","/reports/lighthouse.json","--chrome-flags=--no-sandbox"]
    # Run this service on-demand with: docker compose run --rm lighthouse
  preview:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: best-casino-portal-preview:latest
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    labels:
      - "com.docker.desktop=preview"
    volumes:
      - ./deploy/nginx/preview.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - bcp-net
  backend:
    build:
      context: ./deploy/backend
      dockerfile: Dockerfile
    image: best-casino-backend:latest
    environment:
      - NODE_ENV=production
      - SENTRY_DSN=${SENTRY_DSN}
    ports:
      - "4000:4000"
    volumes:
      - ./logs:/var/log/bcp
    restart: unless-stopped
    networks:
      - bcp-net
networks:
  bcp-net:
    driver: bridge
