/**
 * Casino Domain Mapping
 * Maps casino slugs to their verified authentic domains for Logo.dev & Brandfetch APIs
 * Generated using MCP Sequential Thinking + Context7 analysis
 * 
 * SMART DOMAIN MAPPING - Fixes Logo.dev 404 issues with correct casino domains
 * Last updated: 2025-10-02T12:00:00Z
 */

export const CASINO_DOMAIN_MAPPING: Record<string, string> = {
  // Smart Verified Domains (Generated by MCP Sequential Thinking Analysis)
  'spellwin': 'spellwin.com',
  'winitbet': 'winit.bet', 
  'unlimluck': 'unlimluck.com',
  'mr-pacho': 'mrpacho.com',
  'larabet': 'larabet.com',
  'slotlair': 'slotlair.co.uk',
  'sagaspins': 'sagaspins.com',
  'sambaslots': 'sambaslots.com',
  'rizz': 'rizzcasino.com',
  'n1bet': 'n1bet.com',
  'spincastle': 'spincastle.com',
  'roman': 'romancasino.com',
  'wildrobin': 'wildrobin.com',
  'jet4bet': 'jet4bet.co.uk',
  'vipzino': 'vipzino.com',
  'spellwin-2': 'spellwin.com', // Duplicate uses main domain
  'red': 'theredcasino.com',
  'london': 'londoncasino.co.uk',
  'ivybet': 'ivybet.io',
  'ritzo': 'ritzocasino.com',
  'spingranny': 'spingranny.cz',
  'vincispin': 'vincispin.com',
  'klikki': 'klikkicasino.com',
  'treasure': 'treasurespins.com',
  'spinlander': 'spinlander.co.uk',
  'tiki': 'tikicasino.com',
  'winshark': 'winshark.com',
  'instant': 'instantcasino.com',
  'panda': 'goldenpanda.com',
  'magius': 'magiuscasino.com',
  
  // Legacy Mappings (Keep for backward compatibility)
  'hello-fortune': 'hellofortune32.com',
  'ivybetio': 'fintmo8.com',
  'kings-chip': 'kingschip2.com',
  'pirate-spins': 'piratespins11.com',
  'robocat-de': 'domainmarkt.de',
  'roman-casino': 'clariki1.com',
  'royal-game': 'kingcare.zendesk.com',
  'sagaspins-uk-v2': 'sagaspins22.com',
  'slotit-de': 'bernd-hendl.com',
  'slots-islands': 'slotsislands1.com',
  'spinmama': 'dynara3.com',
  'vegas-nova': 'vegasnova-il.com',
};

/**
 * Get the verified casino domain for Brandfetch API
 * @param slug - Casino slug
 * @param fallbackDomain - Domain extracted from URL as fallback
 * @returns The verified domain to use with Brandfetch
 */
export function getVerifiedCasinoDomain(slug: string, fallbackDomain: string): string {
  // Check if we have a verified domain mapping
  if (CASINO_DOMAIN_MAPPING[slug]) {
    return CASINO_DOMAIN_MAPPING[slug];
  }
  
  // Use the fallback domain from the URL
  return fallbackDomain;
}
