name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Generate images
        run: npm run images:generate || true

      - name: Build site
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist

  lighthouse:
    runs-on: ubuntu-latest
    needs: build_and_test
    env:
      CHROME_PATH: /usr/bin/chromium
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Chromium
        run: sudo apt-get update && sudo apt-get install -y chromium

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist

      - name: Serve dist
        run: npx http-server ./dist -p 8080 -c-1 &

      - name: Run Lighthouse
        run: npx lighthouse http://localhost:8080 --output json --output-path=./reports/lighthouse.json --chrome-flags="--no-sandbox"

      - name: Parse Lighthouse summary
        run: node scripts/parse-lighthouse.js

      - name: Upload Lighthouse summary
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-summary
          path: ./reports/lighthouse-summary.json

      - name: Enforce threshold
        run: |
          node -e "const s=require('./reports/lighthouse-summary.json'); const p=s.categories.performance; if(p<95){console.error('Performance below threshold',p); process.exit(1);} console.log('Performance OK',p);"
